api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from api import routers

app_name = "api"

urlpatterns = [
    path("auth/", obtain_auth_token,name= "api-token"),
    *routers.category_router.urls,
    *routers.product_router.urls,
    *routers.user_router.urls,
    *routers.order_router.urls,
]

cart/urls.py
"""Cart  URL Configuration """
from django.urls import path
from cart.views import cart_add,cart_detail,cart_remove


app_name = "cart"
urlpatterns = [
    path("cart/",cart_detail,name="cart_detail"),
    path("cart_add/<str:slug>",cart_add,name="cart_add"),
    path("cart_remove/<str:slug>",cart_remove,name= "cart_remove"),

]

order/urls.py
from django.urls import path
from order.views import order_create,history
app_name = "order"

urlpatterns = [
    path("order/create/<str:username>/",order_create,name= "order-create"),
    path("order/history/<int:user_id>/",history,name= "order-history"),



]

products/urls.py
"""Product  URL Configuration """
from django.urls import path
from products.views import ProductDetailView, filter_object, FilterDetailView,ProductCreate,ProductUpdate


app_name = "product"
urlpatterns = [
    path("product/create/",ProductCreate.as_view(),name="product-create"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product"),
    path("product/update/<slug:slug>/",ProductUpdate.as_view(),name="product-update"),
    path("filter_by/<str:filter_name>/", filter_object, name="filter-object"),
    path("filter_class/<str:category_id>/", FilterDetailView.as_view(), name="filter-object"),




]

web_market/urls.py
from django.contrib import admin
from django.urls import path, include
from web_market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomepageListView.as_view(), name="homepage"),

    path("", include("order.urls")),
    path("", include("products.urls")),
    path("", include("user.urls")),
    path("", include("cart.urls")),
    path("", include("refund.urls")),
]
handler404 = "web_market.views.page_not_found_view"

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from cart.cart import Cart
from products.models import ProductModel
from cart.forms import CartAddProductForm

# Create your views here.
from django.views.decorators.http import require_POST


@require_POST
def cart_add(request: HttpRequest, slug) -> HttpResponse:
    cart = Cart(request)
    product = get_object_or_404(ProductModel, slug=slug)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd["quantity"],
                 update_quantity=cd["update"])
    return redirect("cart:cart_detail")
def cart_remove(request, slug):
    cart= Cart(request)
    product = get_object_or_404(ProductModel, slug=slug)
    cart.remove(product)
    return redirect("cart:cart_detail")

def cart_detail(request):
    cart = Cart(request)
    context = {"cart":cart}
    return render(request,"cart/detail.html", context)

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block container %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ products.get_absolute_url }}">
                            <img src="{{ product.img }}" width="50" height="50" alt="picture">
                        </a>
                    </td>
                    <td><a href="{% url "product:product" product.slug%}">{{ product.name }}</a></td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.slug%}">Remove</a></td>
                    <td class="num">UAH {{ item.price }}</td>
                    <td class="num">UAH {{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
             <td colspan="0"></td>
            <td class="num"> {{ cart.total_count }}</td>
            <td colspan="2"></td>
            <td class="num">UAH {{ cart.total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "homepage" %}" class="button light">Continue shopping</a>
        {% if  cart.afford_buy %}
        <a href="{% url "order:order-create" username=user.username %}"> <button>Checkout</button> </a>
    {% else %}
    <a href="{% url "order:order-create" username=user.username %}"> <button disabled>Checkout</button> </a>
    </p>
    {% endif %}
{% endblock %}