api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from api import routers

app_name = "api"

urlpatterns = [
    path("auth/", obtain_auth_token,name= "api-token"),
    *routers.category_router.urls,
    *routers.product_router.urls,
    *routers.user_router.urls,
    *routers.order_router.urls,
]

order/urls.py
from django.urls import path
from order.views import order_create,history
app_name = "order"

urlpatterns = [
    path("order/create/<str:username>/",order_create,name= "order-create"),
    path("order/history/<int:user_id>/",history,name= "order-history"),



]

user/urls.py
"""User App URL Configuration """
from django.urls import path, include
from user.views import UserCreateView, UserUpdateView, UserView,UserLoginView,logout_view
# from .api_views import UserViewSet

app_name = "user"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("logout/",logout_view, name="logout"),
    path("<slug:slug>", UserView.as_view(), name="user"),
    path("<slug:slug>/update/", UserUpdateView.as_view(), name="change-data"),
    path("api/",include("api.urls",namespace="api")),
]

web_market/urls.py
from django.contrib import admin
from django.urls import path, include
from web_market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomepageListView.as_view(), name="homepage"),

    path("", include("order.urls")),
    path("", include("products.urls")),
    path("", include("user.urls")),
    path("", include("cart.urls")),
    path("", include("refund.urls")),
]
handler404 = "web_market.views.page_not_found_view"

user/models.py
"""
User application model

"""
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class UserModel(AbstractUser):
    genders = (
        ("m", "Men"),
        ("f", "Women")

    )
    gender = models.CharField(max_length=1, choices=genders, default="")
    age = models.IntegerField(null=True, blank=True, )
    balance = models.IntegerField(null=True, default=10_000)

    class Meta:
        db_table = "auth_user"
        verbose_name = "user"
        verbose_name_plural = "users"

    def get_absolute_url(self):
        return reverse("user:user", kwargs={"slug": self.username})

user/forms.py
"""
User application forms
"""

from django.contrib.auth import forms
from user.models import UserModel


class RegisterForm(forms.UserCreationForm):
    class Meta:
        model = UserModel
        fields = ["username", "first_name", "last_name", "email", "age", "gender", "password1", "password2", ]


class LoginForm(forms.AuthenticationForm):
    class Meta:
        model = UserModel
        fields = ["username", "password"]


class Edit_LoginForm(forms.UserChangeForm):
    class Meta:
        model = UserModel
        fields = ["username", "password", "first_name", "last_name", "email", "age", "gender", ]

user/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DetailView
from user.forms import RegisterForm, LoginForm
from user.models import UserModel


class UserLoginView(LoginView):
    model = UserModel
    form_class = LoginForm
    template_name = "login.html"


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return HttpResponseRedirect(reverse("homepage"))


class UserView(DetailView):
    model = UserModel
    template_name = "user_profile.html"

    def get_object(self, **kwargs):
        return UserModel.objects.get(username=self.kwargs['slug'])


class UserCreateView(CreateView):
    model = UserModel
    form_class = RegisterForm
    template_name = "register.html"
    success_url = "/"


class UserUpdateView(UpdateView):
    model = UserModel
    form_class = RegisterForm
    template_name = "register.html"

    def get_object(self, **kwargs):
        return UserModel.objects.get(username=self.kwargs['slug'])

user/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block container %}
    <div>Message: {{ message }}</div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

user/templates/register.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block container %}
    <div>Message: {{ message }}</div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>


{% endblock %}

user/templates/user_profile.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block container %}
    <h1>User profile:{{ user.username }} </h1>
    <hr>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
    <a href="{% url "user:change-data" slug=object.username %}">
        <button>Edit data</button>
    </a>
    <a href="{% url "order:order-history" user_id=usermodel.id %}" class="button">history</a>

    <img src="https://cdn.icon-icons.com/icons2/2506/PNG/512/user_icon_150670.png" width="200" height="200"
         alt="picture">
    <div><span style="font-size:35px;color: gray">username:</span> <span
            style="font-size: 30px; ">{{ user.username }}</span></div>
    <div><span style="font-size:35px;color: gray">First Name:</span> <span
            style="font-size: 30px; ">{{ user.first_name }}</span></div>
    <div><span style="font-size:35px;color: gray">Last Name:</span> <span
            style="font-size: 30px; ">{{ user.last_name }}</span></div>
    <div><span style="font-size:35px;color: gray">Email:</span> <span
            style="font-size: 30px; ">{{ user.email }}</span></div>
    <div><span style="font-size:35px;color: gray">Age:</span> <span
            style="font-size: 30px; ">{{ user.age }}</span></div>
    <div><span style="font-size:35px;color: gray">Gender:</span> <span
            style="font-size: 30px; ">{{ user.gender }}</span></div>
    <div><span style="font-size:35px;color: gray">Balance:</span> <span
        style="font-size: 30px; ">{{ user.balance }}</span></div>


{% endblock %}