api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from api import routers

app_name = "api"

urlpatterns = [
    path("auth/", obtain_auth_token,name= "api-token"),
    *routers.category_router.urls,
    *routers.product_router.urls,
    *routers.user_router.urls,
    *routers.order_router.urls,
]

cart/urls.py
"""Cart  URL Configuration """
from django.urls import path
from cart.views import cart_add,cart_detail,cart_remove


app_name = "cart"
urlpatterns = [
    path("cart/",cart_detail,name="cart_detail"),
    path("cart_add/<str:slug>",cart_add,name="cart_add"),
    path("cart_remove/<str:slug>",cart_remove,name= "cart_remove"),

]

products/urls.py
"""Product  URL Configuration """
from django.urls import path
from products.views import ProductDetailView, filter_object, FilterDetailView,ProductCreate,ProductUpdate


app_name = "product"
urlpatterns = [
    path("product/create/",ProductCreate.as_view(),name="product-create"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product"),
    path("product/update/<slug:slug>/",ProductUpdate.as_view(),name="product-update"),
    path("filter_by/<str:filter_name>/", filter_object, name="filter-object"),
    path("filter_class/<str:category_id>/", FilterDetailView.as_view(), name="filter-object"),




]

user/urls.py
"""User App URL Configuration """
from django.urls import path, include
from user.views import UserCreateView, UserUpdateView, UserView,UserLoginView,logout_view
# from .api_views import UserViewSet

app_name = "user"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("logout/",logout_view, name="logout"),
    path("<slug:slug>", UserView.as_view(), name="user"),
    path("<slug:slug>/update/", UserUpdateView.as_view(), name="change-data"),
    path("api/",include("api.urls",namespace="api")),
]

web_market/urls.py
from django.contrib import admin
from django.urls import path, include
from web_market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomepageListView.as_view(), name="homepage"),

    path("", include("order.urls")),
    path("", include("products.urls")),
    path("", include("user.urls")),
    path("", include("cart.urls")),
    path("", include("refund.urls")),
]
handler404 = "web_market.views.page_not_found_view"

products/models.py
from django.db import models
from django.urls import reverse


class CategoryModel(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True, max_length=30)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"
        ordering = "slug",
        db_table = "products_categorymodel"


class ProductModel(models.Model):
    name = models.CharField(max_length=20, blank=True)
    slug = models.SlugField(unique=True, max_length=20, blank=True)
    price = models.PositiveIntegerField(blank=True)
    description = models.TextField(blank=True)
    count = models.PositiveIntegerField(blank=True)
    available = models.BooleanField(blank=True)
    img = models.URLField(blank=True)
    category = models.ForeignKey("CategoryModel", on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "product"
        verbose_name_plural = "products"
        ordering = "slug",
        db_table = "product_base"

    def get_absolute_url(self):
        return reverse('product:product',
                       kwargs={"slug":self.slug})

products/forms.py
from django import forms

from products.models import ProductModel


class ProductForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = "__all__"
    # def clean_slug(self):
    #     new_slug = self.cleaned_data["slug"].lower()
    #     if new_slug == "create":
    #         raise ValidationError("slug can not be 'create'")

products/views.py
from django.http import HttpResponse, HttpRequest, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import DetailView, ListView, CreateView
from cart.forms import CartAddProductForm
from .forms import ProductForm
from .models import ProductModel
from .utils import ObjectCreateMixin,ObjecttUpdateMixin


class ProductCreate(ObjectCreateMixin, View):
    model = ProductModel
    template = "create_update_form.html"

class ProductUpdate(ObjecttUpdateMixin,View):
    model = ProductModel

    template = "create_update_form.html"

class ProductDetailView(DetailView):
    model = ProductModel
    template_name = "product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_product_form = CartAddProductForm()
        context["object_list"] = cart_product_form
        return context

    def get_object(self, **kwargs):
        return ProductModel.objects.get(slug=self.kwargs['slug'])


def filter_object(request: HttpRequest, filter_name) -> HttpResponse:
    if filter_name == "available":
        element_product = ProductModel.objects.filter(available=True)
    elif filter_name == "50k":
        element_product = ProductModel.objects.filter(price__lt=50000)
    elif filter_name == "50k-99k":
        element_product = ProductModel.objects.filter(price__range=(50_000, 99_000))
    elif filter_name == "99k-200k":
        element_product = ProductModel.objects.filter(price__range=(99_000, 200_000))
    elif filter_name == "200k-":
        element_product = ProductModel.objects.filter(price__gte=200_000)
    context = {"object_list": element_product}
    return render(request, "homepage.html", context)


class FilterDetailView(ListView):
    model = ProductModel
    template_name = "homepage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = ProductModel.objects.filter(category_id=self.kwargs['category_id'])
        return context

products/templates/create_update_form.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block container %}

    <form action="{{ item.get_absolute_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
    </form>

{% endblock %}

products/templates/filters_button.html
<div style="text-align: right;">
    <form action="/filter_by/available/" target="_self">
        <button class="new">По наличию</button>
    </form>
    <form>
        <div class="dropdown">
            <form>
                <button disabled class="new"> Price</button>
                <i class="fa fa-caret-down"></i>
            </form>
            <div class="dropdown-content">
                <form action="/filter_by/50k" target="_self">
                    <button class="new">for 0 to 50000</button>
                </form>
                <form action="/filter_by/50k-99k" target="_self">
                    <button class="new">for 50.000 - 99.0000</button>
                </form>
                <form action="/filter_by/99k-200k" target="_self">
                    <button class="new">for 99.000 - 200.000</button>
                </form>
                <form action="/filter_by/200k-" target="_self">
                    <button class="new">for 200.000 to ...</button>
                </form>
            </div>
        </div>
        <div class="dropdown">
            <button class="new">Category
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <form action="/filter_class/1" target="_self">
                    <button class="new">Robots</button>
                </form>
                <form action="/filter_class/2" target="_self">
                    <button class="new">Star Wars</button>
                </form>
                <form action="/filter_class/3" target="_self">
                    <button class="new">Cartoon</button>
                </form>
                <form action="/filter_class/4" target="_self">
                    <button class="new">Film</button>
                </form>
                <form action="/filter_class/5" target="_self">
                    <button class="new">Game</button>
                </form>
            </div>
        </div>
    </form>
</div>

products/templates/product.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block container %}
    <style>
        .b_color {
            background: navy;
            color: antiquewhite;
            width: 200px;
            height: 25px;
        }
    </style>
    <img src="{{ object.img }}" width="300" height="300"
         alt="picture">
    <hr>
    <h1>Robot: {{ object.name }} </h1>
    <div><span style="font-size:35px;color: black">Description: </span> <span
            style="font-size: 30px; ">{{ object.description }}</span></div>
    <div><span style="font-size:35px;color: crimson">Price:</span> <span
            style="font-size: 30px; ">{{ object.price }}</span>
    </div>
    <div><span style="font-size:35px;color: crimson">Count:</span> <span
            style="font-size: 30px; ">{{ object.count }}</span>
    </div>
    {% if user.is_staff %}
        <div>
            <a href="{% url "product:product-update" object.slug%}">
                <button>Update item</button>

        </a></div>
    {% endif %}

    {% if  object.available %}
        {% if not user.is_authenticated %}
            <form action="{% url "user:login" %}" >
                    <input type="submit" value="Add to cart">
                </form>
            {% else %}
                <form action="{% url "cart:cart_add" object.slug %}" method="post">
           {{ object_list }}
           {% csrf_token %}
           <input type="submit" value="Add to cart">
        </form>

            {% endif %}


    {% else %}
        <div><span style="font-size:35px;color: gray">Available:</span><span style="font-size: 30px; ">None</span></div>
        <p>
            <button disabled>Buy</button>
        </p>


    {% endif %}

{% endblock %}

products/templates/thistest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>sdasdsadsadsaddsadasdsadsadsadsadsadsaad
<body>

</body>
</html>