api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from api import routers

app_name = "api"

urlpatterns = [
    path("auth/", obtain_auth_token,name= "api-token"),
    *routers.category_router.urls,
    *routers.product_router.urls,
    *routers.user_router.urls,
    *routers.order_router.urls,
]

cart/urls.py
"""Cart  URL Configuration """
from django.urls import path
from cart.views import cart_add,cart_detail,cart_remove


app_name = "cart"
urlpatterns = [
    path("cart/",cart_detail,name="cart_detail"),
    path("cart_add/<str:slug>",cart_add,name="cart_add"),
    path("cart_remove/<str:slug>",cart_remove,name= "cart_remove"),

]

products/urls.py
"""Product  URL Configuration """
from django.urls import path
from products.views import ProductDetailView, filter_object, FilterDetailView,ProductCreate,ProductUpdate


app_name = "product"
urlpatterns = [
    path("product/create/",ProductCreate.as_view(),name="product-create"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product"),
    path("product/update/<slug:slug>/",ProductUpdate.as_view(),name="product-update"),
    path("filter_by/<str:filter_name>/", filter_object, name="filter-object"),
    path("filter_class/<str:category_id>/", FilterDetailView.as_view(), name="filter-object"),




]

refund/urls.py
from django.urls import path
from refund.views import refund_order, all_orders_refund, accept_refund, decline_refund

app_name = "refund"

urlpatterns = [
    path("refund/<str:order_id>/", refund_order, name="refund-order"),
    path("all_refunds/", all_orders_refund, name="all-orders"),
    path("accept_refund/<str:order_id>/", accept_refund, name="accept-refund"),
    path("decline_refun/<str:order_id>/", decline_refund, name="decline-refund"),

]

user/urls.py
"""User App URL Configuration """
from django.urls import path, include
from user.views import UserCreateView, UserUpdateView, UserView,UserLoginView,logout_view
# from .api_views import UserViewSet

app_name = "user"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("logout/",logout_view, name="logout"),
    path("<slug:slug>", UserView.as_view(), name="user"),
    path("<slug:slug>/update/", UserUpdateView.as_view(), name="change-data"),
    path("api/",include("api.urls",namespace="api")),
]

web_market/urls.py
from django.contrib import admin
from django.urls import path, include
from web_market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomepageListView.as_view(), name="homepage"),

    path("", include("order.urls")),
    path("", include("products.urls")),
    path("", include("user.urls")),
    path("", include("cart.urls")),
    path("", include("refund.urls")),
]
handler404 = "web_market.views.page_not_found_view"

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from cart.cart import Cart
from products.models import ProductModel
from cart.forms import CartAddProductForm

# Create your views here.
from django.views.decorators.http import require_POST


@require_POST
def cart_add(request: HttpRequest, slug) -> HttpResponse:
    cart = Cart(request)
    product = get_object_or_404(ProductModel, slug=slug)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd["quantity"],
                 update_quantity=cd["update"])
    return redirect("cart:cart_detail")
def cart_remove(request, slug):
    cart= Cart(request)
    product = get_object_or_404(ProductModel, slug=slug)
    cart.remove(product)
    return redirect("cart:cart_detail")

def cart_detail(request):
    cart = Cart(request)
    context = {"cart":cart}
    return render(request,"cart/detail.html", context)

templates/base.html
{#Mother of all html files with button cart/profile/homepage#}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Default tittle {% endblock %}</title>
    <style>
        ul {
            list-style: none; /*убираем маркеры списка*/
            margin: 0; /*убираем отступы*/
            padding-left: 0; /*убираем отступы*/
        }

        a {
            text-decoration: none; /*убираем подчеркивание текста ссылок*/
        }

        li {
            float: left; /*Размещаем список горизонтально для реализации меню*/
            margin-right: 5px; /*Добавляем отступ у пунктов меню*/
        }
    </style>
</head>
<body>
<header class="active-user">Active user: {{ user }}</header>
<nav class="one">
    <ul>
        <li><a>
            <form action="/" target="_self">
                <button>Home</button>
            </form>
        </a></li>
        <li>
            <a href="{% url "cart:cart_detail" %}">
                <button>Cart</button>

            </a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url "user:user" slug=user.username %}">
                <button>{{ user.username }}</button>
            </a></li>
            <li><a href="{% url "user:logout" %}">
                <button>Logout</button>
            </a></li>
        {% else %}
            <li><a href="{% url "user:login" %}">
                <button>Login</button>
            </a></li>
            <li><a href="{% url "user:register" %}">
                <button>Register</button>
            </a></li>
        {% endif %}
        {% if user.is_staff %}
            <li>
                <a href="{% url "product:product-create" %}">
                    <button>Create item</button>

                </a></li>
            <li>
                <a href="{% url "refund:all-orders" %}">
                    <button>Refunds</button>

                </a></li>
        {% endif %}

    </ul>
</nav>
</body>
<div class="container ">
    {% block container %}{% endblock %}
</div>
</html>

templates/cart.html
{# This html for cart in web market #}
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block container %}
    {% include "styles_web/style_cart.html" %}
    <title>Cart</title>

    <table border="5">
        <tbody>
        <tr>
            {#            exectly this will be 30 px#}
            <td width="30px">№</td>
            <td>id</td>
            <td>Name</td>
            <td>price</td>
        </tr>


        </tbody>
    </table>



{% endblock %}

templates/homepage.html
{#Html home page / catalog of products#}
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block container %}
    {% include "styles_web/style_hompage.html" %}
    <h1 align="center">Catalog</h1>
    <hr color="black">
    {% include "filters_button.html" %}
    {% for el in object_list %}

        {% if not el.available %}
            <figure class="passe-partout" style="background: dimgrey">
        {% else %}
            <figure class="passe-partout">
        {% endif %}
           <img src={{ el.img }} width="200" height="231" alt={{ el.name }}
                    class="passe-partout">
            <h1>Robot: {{ el.name }} </h1>
            <div><span style="font-size:35px;color: crimson">Price:</span> <span
                    style="font-size: 30px; "> {{ el.price }} </span>
            </div>
            {% if not el.available %}
                <h2>not available</h2>
            {% endif %}
            <a href="{% url "product:product" slug=el.slug %}">
                <p>
                    <button class="new">More</button>
                </p>
            </a>
        </figure>









    {% endfor %}
{% endblock %}